version: '3'
services:
  nestjs-be:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
